/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRegistrationForm {
    }
    interface AppRoot {
    }
    interface FocusNext {
        "nextInputId": string;
    }
    interface InputNumeric {
    }
}
declare global {
    interface HTMLAppRegistrationFormElement extends Components.AppRegistrationForm, HTMLStencilElement {
    }
    var HTMLAppRegistrationFormElement: {
        prototype: HTMLAppRegistrationFormElement;
        new (): HTMLAppRegistrationFormElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLFocusNextElement extends Components.FocusNext, HTMLStencilElement {
    }
    var HTMLFocusNextElement: {
        prototype: HTMLFocusNextElement;
        new (): HTMLFocusNextElement;
    };
    interface HTMLInputNumericElement extends Components.InputNumeric, HTMLStencilElement {
    }
    var HTMLInputNumericElement: {
        prototype: HTMLInputNumericElement;
        new (): HTMLInputNumericElement;
    };
    interface HTMLElementTagNameMap {
        "app-registration-form": HTMLAppRegistrationFormElement;
        "app-root": HTMLAppRootElement;
        "focus-next": HTMLFocusNextElement;
        "input-numeric": HTMLInputNumericElement;
    }
}
declare namespace LocalJSX {
    interface AppRegistrationForm {
    }
    interface AppRoot {
    }
    interface FocusNext {
        "nextInputId"?: string;
    }
    interface InputNumeric {
    }
    interface IntrinsicElements {
        "app-registration-form": AppRegistrationForm;
        "app-root": AppRoot;
        "focus-next": FocusNext;
        "input-numeric": InputNumeric;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-registration-form": LocalJSX.AppRegistrationForm & JSXBase.HTMLAttributes<HTMLAppRegistrationFormElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "focus-next": LocalJSX.FocusNext & JSXBase.HTMLAttributes<HTMLFocusNextElement>;
            "input-numeric": LocalJSX.InputNumeric & JSXBase.HTMLAttributes<HTMLInputNumericElement>;
        }
    }
}
